version: "3.8"

services:
  app:
    build: .
    container_name: scheduler-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/scheduler
    networks:
      - scheduler-net

  mongo:
    image: mongo:latest
    container_name: scheduler-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - scheduler-net

volumes:
  mongo-data:

networks:
  scheduler-net: